libdrm-nvdc: set DEBIAN_NOAUTONAME also for source package
This is needed to avoid spdx from failing during sdk build with:
  Exception: FileNotFoundError: [Errno 2] No such file or directory: 'tmp/deploy/spdx/by-hash/sstate:libdrm-nvdc:armv8a_tegra-poky-linux:35.3.1-20230319081403:r0:armv8a_tegra:11:/libdrm-src.spdx.json

Signed-off-by: Samuli Piippo <samuli.piippo@qt.io>