tegra-helper-scripts: Check for dtc
Verify that the dtc command is available, and if not, display
a user-friendly error message recommending installation of the
'device-tree-compiler' package.

This avoids running in the following error due to missing dtc:

FileNotFoundError: [Errno 2] No such file or directory: 'dtc'

Signed-off-by: Leon Anavi <leon.anavi@konsulko.com>