image_types_tegra.bbclass: Deploy cboot.bin
For Jetson TX2, the default configuration uses cboot to load
U-Boot. Script doflash.sh requires cboot.bin. If it is not
present the scripts fails with:

Error: Return value 4

This fix ensures that task do_deploy of cboot will be executed
and cboot.bin will be present even if U-Boot has been selected
as a bootloader.

Signed-off-by: Leon Anavi <leon.anavi@konsulko.com>