cuda-toolkit: add COMPATIBLE_MACHINE restriction
* fixes:
NOTE: Resolving any missing task queue dependencies
cuda-cudart was skipped: incompatible with machine qemux86 (not in COMPATIBLE_MACHINE)
ERROR: Required build target 'meta-world-pkgdata' has no buildable providers.
Missing or unbuildable dependency chain was: ['meta-world-pkgdata', 'cuda-toolkit', 'cuda-cudart']

cuda-core was skipped: incompatible with machine qemux86 (not in COMPATIBLE_MACHINE)
ERROR: Required build target 'meta-world-pkgdata' has no buildable providers.
Missing or unbuildable dependency chain was: ['meta-world-pkgdata', 'cuda-toolkit', 'cuda-core']

cuda-npp was skipped: incompatible with machine qemux86 (not in COMPATIBLE_MACHINE)
ERROR: Required build target 'meta-world-pkgdata' has no buildable providers.
Missing or unbuildable dependency chain was: ['meta-world-pkgdata', 'cuda-toolkit', 'cuda-npp']

Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>
Signed-off-by: Matt Madison <matt@madison.systems>