tegra-uefi-capsules: add missing dependency
There was a missing dependency to edk2-firmware-rcmboot. Use the variable
TEGRA_RCM_EDK2_DEPENDS that is defined in tegra-common.inc and either
resolves to virtual/bootloader:do_deploy or edk2-firmware-rcmboot:do_deploy
depending on configuration.

To reproduce the error start a fresh build in a clean build directory:
  $ bitbake tegra-uefi-capsules
  ...
  | cp: cannot stat '<snip>/tmp/deploy/images/jetson-agx-thor-devkit/uefi_t26x_rcmboot.bin': No such file or directory
  | WARNING: exit code 1 from a shell command.
  ERROR: Task (<snip>/meta-tegra/recipes-bsp/uefi/tegra-uefi-capsules_38.4.0.bb:do_compile) failed with exit code '1'

Signed-off-by: Peter Bergin <peter@berginkonsult.se>