tegra*-flashtools-native: remove dependency on tegra-binaries
* native recipe shouldn't depend on target tegra-binaries.do_preconfigure
  especially for MACHINEs which aren't tegra, e.g. qemuarm fails to build
  tegra210-flashtools-native with:
  ERROR: Nothing PROVIDES 'tegra-binaries'
  ERROR: tegra-binaries was skipped: incompatible with machine qemuarm (not in COMPATIBLE_MACHINE)
  ERROR: tegra-binaries was skipped: incompatible with machine qemuarm (not in COMPATIBLE_MACHINE)
  ERROR: Required build target 'tegra-flashtools-native' has no buildable providers.
  Missing or unbuildable dependency chain was: ['tegra-flashtools-native', 'tegra-binaries']

Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>