setup-nv-boot-control: add COMPAT_TARGET
From discussion at [1], NVIDIA hard-codes a check for
COMPATIBLE_SPEC into nvbootctrl in order to determine
whether to use EFI variables in emmc.

For custom MACHINEs which use a custom TARGET that
doesn't match the `unify_name` value in the
`nv-l4t-bootloader-config.sh` script, this means any
attempt to set bootloader slot from nvbootctrl, for
instance the attempt to set slots as an alternative
to capsule update with [2], fail with
```
Error: open fail errno = 30 reason = Read-only file system
Error: write variable BootChainFwNext failed!
```

Add a COMPAT_TARGET to the setup-nv-boot-control script
which by default is set to TARGET.  However, if using
a custom MACHINE/TARGET which is based on
`jetson_agx_xavier_devkit` you can define:
```
TNSPEC_COMPAT_MACHINE = "jetson-agx-xavier-devkit"
```
in your machine configuration and nvbootctrl will
work as expected, where `jetson-agx-xavier-devkit`
is the value of `unify_name` in `nv-l4t-bootloader-config.sh`
in the Jetpack release sources from nvidia for
`jetson_agx_xavier_devkit` target.

1: https://forums.developer.nvidia.com/t/nvbootctrl-hardcoded-to-only-handle-agx-xavier/270411/4
2: https://github.com/OE4T/tegra-demo-distro/pull/320

Signed-off-by: Dan Walkes <danwalkes@trellis-logic.com>