cuda-command-line-tools: add dependency on expat
* it's not really build time dependency as this is prebuilt, but it fixes following QA issue:
  ERROR: QA Issue: cuda-command-line-tools rdepends on expat, but it isn't a build dependency, missing expat in DEPENDS or PACKAGECONFIG? [build-deps]
  and using DEPENDS instead of RDEPENDS helps do_package shlibs code to properly find
  shlib provider for expat library

Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>
Signed-off-by: Matt Madison <matt@madison.systems>