linux-tegra-4.4: disable format-truncation, duplicate-decl-specifier, int-in-bool-context warnings
* like tegra186 in linux-tegra-3.10 we need to disable few warnings to
  build successfully with gcc-7, hide following errors:
  TOPDIR/BUILD/work-shared/jetson-tx1/kernel-source/drivers/input/keyboard/atkbd.c:1071:4: error: '/input0' directive output may be truncated writing 7 bytes into a region of size between 1 and 32 [-Werror=format-truncation=]
  TOPDIR/BUILD/work-shared/jetson-tx1/kernel-source/drivers/media/platform/tegra/camera/vi/channel.c:1035:60: error: '%s' directive output may be truncated writing up to 31 bytes into a region of size 21 [-Werror=format-truncation=]
  TOPDIR/BUILD/work-shared/jetson-tx1/kernel-source/drivers/media/platform/tegra/camera/vi/channel.c:1059:61: error: '%s' directive output may be truncated writing up to 31 bytes into a region of size 21 [-Werror=format-truncation=]
  TOPDIR/BUILD/work-shared/jetson-tx1/kernel-source/drivers/usb/gadget/udc/tegra_xudc.c:309:19: error: duplicate 'const' declaration specifier [-Werror=duplicate-decl-specifier]
  TOPDIR/BUILD/work-shared/jetson-tx1/kernel-source/drivers/video/tegra/../../../nvidia/display/drivers/video/tegra/dc/dsi.c:884:34: error: '*' in boolean context, suggest '&&' instead [-Werror=int-in-bool-context]
  TOPDIR/BUILD/work-shared/jetson-tx1/kernel-source/drivers/video/tegra/../../../nvidia/display/drivers/video/tegra/dc/dsi.c:888:38: error: '*' in boolean context, suggest '&&' instead [-Werror=int-in-bool-context]
  TOPDIR/BUILD/work-shared/jetson-tx1/kernel-source/drivers/video/tegra/../../../nvidia/display/drivers/video/tegra/dc/dsi.c:892:37: error: '*' in boolean context, suggest '&&' instead [-Werror=int-in-bool-context]
  TOPDIR/BUILD/work-shared/jetson-tx1/kernel-source/drivers/video/tegra/../../../nvidia/display/drivers/video/tegra/dc/dsi.c:896:37: error: '*' in boolean context, suggest '&&' instead [-Werror=int-in-bool-context]
  TOPDIR/BUILD/work-shared/jetson-tx1/kernel-source/drivers/video/tegra/../../../nvidia/display/drivers/video/tegra/dc/dsi.c:900:40: error: '*' in boolean context, suggest '&&' instead [-Werror=int-in-bool-context]
  TOPDIR/BUILD/work-shared/jetson-tx1/kernel-source/drivers/video/tegra/../../../nvidia/display/drivers/video/tegra/dc/dsi.c:904:36: error: '*' in boolean context, suggest '&&' instead [-Werror=int-in-bool-context]
  TOPDIR/BUILD/work-shared/jetson-tx1/kernel-source/drivers/video/tegra/../../../nvidia/display/drivers/video/tegra/dc/dsi.c:912:34: error: '*' in boolean context, suggest '&&' instead [-Werror=int-in-bool-context]
  TOPDIR/BUILD/work-shared/jetson-tx1/kernel-source/drivers/video/tegra/../../../nvidia/display/drivers/video/tegra/dc/dsi.c:916:37: error: '*' in boolean context, suggest '&&' instead [-Werror=int-in-bool-context]
  TOPDIR/BUILD/work-shared/jetson-tx1/kernel-source/drivers/video/tegra/../../../nvidia/display/drivers/video/tegra/dc/dsi.c:920:37: error: '*' in boolean context, suggest '&&' instead [-Werror=int-in-bool-context]
  TOPDIR/BUILD/work-shared/jetson-tx1/kernel-source/drivers/video/tegra/../../../nvidia/display/drivers/video/tegra/dc/dsi.c:924:37: error: '*' in boolean context, suggest '&&' instead [-Werror=int-in-bool-context]
  TOPDIR/BUILD/work-shared/jetson-tx1/kernel-source/drivers/video/tegra/../../../nvidia/display/drivers/video/tegra/dc/dsi.c:928:39: error: '*' in boolean context, suggest '&&' instead [-Werror=int-in-bool-context]
  TOPDIR/BUILD/work-shared/jetson-tx1/kernel-source/drivers/video/tegra/../../../nvidia/display/drivers/video/tegra/dc/dsi.c:936:34: error: '*' in boolean context, suggest '&&' instead [-Werror=int-in-bool-context]
  TOPDIR/BUILD/work-shared/jetson-tx1/kernel-source/drivers/video/tegra/../../../nvidia/display/drivers/video/tegra/dc/dsi.c:944:34: error: '*' in boolean context, suggest '&&' instead [-Werror=int-in-bool-context]
  TOPDIR/BUILD/work-shared/jetson-tx1/kernel-source/drivers/video/tegra/../../../nvidia/display/drivers/video/tegra/dc/dsi.c:948:35: error: '*' in boolean context, suggest '&&' instead [-Werror=int-in-bool-context]
  TOPDIR/BUILD/work-shared/jetson-tx1/kernel-source/drivers/video/tegra/../../../nvidia/display/drivers/video/tegra/dc/dsi.c:952:36: error: '*' in boolean context, suggest '&&' instead [-Werror=int-in-bool-context]
  TOPDIR/BUILD/work-shared/jetson-tx1/kernel-source/drivers/video/tegra/../../../nvidia/display/drivers/video/tegra/dc/dsi.c:956:34: error: '*' in boolean context, suggest '&&' instead [-Werror=int-in-bool-context]
  TOPDIR/BUILD/work-shared/jetson-tx1/kernel-source/drivers/video/tegra/../../../nvidia/display/drivers/video/tegra/dc/dsi.c:964:34: error: '*' in boolean context, suggest '&&' instead [-Werror=int-in-bool-context]
  TOPDIR/BUILD/work-shared/jetson-tx1/kernel-source/drivers/video/tegra/../../../nvidia/display/drivers/video/tegra/dc/dsi.c:968:36: error: '*' in boolean context, suggest '&&' instead [-Werror=int-in-bool-context]

Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>