cuda-binaries: define CUDA_VERSION
* the native recipes don't have COMPATIBLE_MACHINE restriction
  so they might be built by some MACHINE which don't define
  CUDA_VERSION at all
* causing preconfigure failures like this:
  ERROR: cuda-binaries-native-8.0.34-1-r0 do_preconfigure: Function failed: do_preconfigure (log file is located at BUILD/work-shared/cuda-binaries-native-8.0.34-1-r0/temp/log.do_preconfigure.9163)
  ERROR: Logfile of failure stored in: BUILD/work-shared/cuda-binaries-native-8.0.34-1-r0/temp/log.do_preconfigure.9163
  Log data follows:
  | DEBUG: Executing shell function do_preconfigure
  | dpkg-deb: error: failed to read archive 'BUILD/work-shared/cuda-binaries-native-8.0.34-1-r0/var/cuda-repo--local/cuda-license-_8.0.34-1_amd64.deb': No such file or directory
  | WARNING: exit code 2 from a shell command.
  | ERROR: Function failed: do_preconfigure (log file is located at BUILD/work-shared/cuda-binaries-native-8.0.34-1-r0/temp/log.do_preconfigure.9163)
  NOTE: recipe cuda-binaries-native-8.0.34-1-r0: task do_preconfigure: Failed
  ERROR: Task (meta-tegra/recipes-devtools/cuda/cuda-binaries-native_8.0.34-1.bb:do_preconfigure) failed with exit code '1'

Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>