linux-tegra: Fix compilation errors
The following compilation errors are present on master branch, and are
due to commit 7f06a747.  The solution removes flags that are not
supported by the toolchain.

cc1: error: -Werror=switch-unreachable: no option -Wswitch-unreachable
cc1: error: -Werror=format-truncation: no option -Wformat-truncation
cc1: error: -Werror=format-overflow: no option -Wformat-overflow
cc1: error: -Werror=int-in-bool-context: no option -Wint-in-bool-context