Fix transaction check errors with libvisionworks
Attempts to build an SDK with libvisionworks included along with other
packages which use pkgconfig fail with:

Error: Transaction check error:
  file /usr/lib/pkgconfig from install of libvisionworks-dev-1.6.0.500n-r0.armv8a_tegra186 conflicts with file from package spdlog-dev-1.3.1-r0.aarch64
  file /usr/lib/pkgconfig conflicts between attempted installs of libvisionworks-dev-1.6.0.500n-r0.armv8a_tegra186 and librealsense2-dev-2.13.0-r0.aarch64
  file /usr/lib/pkgconfig conflicts between attempted installs of cuda-command-line-tools-dev-10.0.166+1-r0.armv8a_tegra186 and libvisionworks-dev-1.6.0.500n-r0.armv8a_tegra186

Solution is to use install -d for ${libdir}/pkgconfig instead of cp -R
--preserve copy