python3-tensorrt: fix linking issue and add run-time dependency
Issue when trying to use python3-tensorrt on a Thor target:

    # python3
    Python 3.14.3 (main, Feb  3 2026, 15:32:20) [GCC 15.2.0] on linux
    Type "help", "copyright", "credits" or "license" for more information.
    >>> import tensorrt
    Traceback (most recent call last):
      File "<python-input-0>", line 1, in <module>
        import tensorrt
      File "/usr/lib/python3.14/site-packages/tensorrt/__init__.py", line 96, in <module>
        from .tensorrt import *
    ImportError: /usr/lib/python3.14/site-packages/tensorrt/tensorrt.so: undefined symbol: getNvOnnxParserVersion

This was caused by not telling cmake where to find that library during linking as the variables
TRT_NVINFER_NAME and TRT_ONNXPARSER_NAME was empty and not initialized. Pass them to the build
with EXTRA_OECMAKE.

Also add tensorrt-plugins to RDEPENDS to ensure libnvonnxparser and
libnvinfer_plugin are present on the target at runtime.

Signed-off-by: Peter Bergin <peter.bergin@1x.tech>
Signed-off-by: Peter Bergin <peter@berginkonsult.se>