Tegra*-minimal-initramfs: Correct referenct to machine
Correct machine definition
1) used by images to making destinction between the SOC family
    defnition and the actual machine name.
2) Using hypen in python variable names is not recommended, as literal
    interprteation is not guaranteed

iyad@2f6883c1d561:/home/build_tegra> bitbake -e  tegra210-minimal-initramfs
ERROR:  OE-core's config sanity checker detected a potential misconfiguration.
    Either fix the cause of this error or at your own risk disable the checker (see sanity.conf).
    Following is the list of potential problems / advisories:

    MACHINE=tegra210 is invalid. Please set a valid MACHINE in your local.conf, environment or other configuration file.

iyad@2f6883c1d561:/home/build_tegra> bitbake core-image-minimal -e
ERROR:  OE-core's config sanity checker detected a potential misconfiguration.
    Either fix the cause of this error or at your own risk disable the checker (see sanity.conf).
    Following is the list of potential problems / advisories:

    MACHINE=tegra124 is invalid. Please set a valid MACHINE in your local.conf, environment or other configuration file.

iyad@2f6883c1d561:/home/build_tegra> bitbake core-image-minimal -e
ERROR:  OE-core's config sanity checker detected a potential misconfiguration.
    Either fix the cause of this error or at your own risk disable the checker (see sanity.conf).
    Following is the list of potential problems / advisories:

    MACHINE=tegra186 is invalid. Please set a valid MACHINE in your local.conf, environment or other configuration file.

iyad@2f6883c1d561:/home/build_tegra> bitbake core-image-minimal -e
ERROR:  OE-core's config sanity checker detected a potential misconfiguration.
    Either fix the cause of this error or at your own risk disable the checker (see sanity.conf).
    Following is the list of potential problems / advisories:

    MACHINE=tegra210 is invalid. Please set a valid MACHINE in your local.conf, environment or other configuration file.